### PR TITLE
Fixed some stuff?

### PR DESCRIPTION
**Pull request by NikNikovsky**
Maybe it is fixed, maybe it is not. Hopefully it is.

### CODE REVIEW

**Review by thetechxplore — CHANGES_REQUESTED** [review]
Add a Backtick Quote around ${randomResponse} and i can approve the code

**Comment by NikNikovsky** [comment]
@thetechxplore done!

**Comment by thetechxplore** [comment]
@NikNikovsky You put the backticks inside the brackets, which won't work. Set One before the `$` and one after the variables closing bracket. Should look like this in the end
\`${randomResponse}`

**Comment by NikNikovsky** [comment]
done?

**Review by thetechxplore — APPROVED** [review]
The Code has been Fixed, and the code will now be updated

**Pull request merged**
